#!/usr/bin/env bash
# spike/inventory.sh
#
# SwiftUI API usage inventory for the Linux port spike (Phase 0).
# Scans Sources/HermesDesktop/Views/ and reports every SwiftUI API call that
# may not be supported on a SwiftCrossUI / Qt6Backend port.
#
# Output: a markdown table grouped by category, with per-API counts and the
# first file:line citation for each match. Cross-referenced against the
# SwiftCrossUI API surface in api-gap-analysis.md.
#
# Requires: ripgrep (rg).

# Intentionally NOT using `set -e` or `set -o pipefail`: ripgrep returns 1
# when a section has zero matches, which is normal here (we deliberately
# search for APIs that might not be used). `set -u` catches typos in shell
# vars without breaking the pipeline.
set -u

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VIEWS_DIR="$REPO_ROOT/Sources/HermesDesktop/Views"
MODELS_DIR="$REPO_ROOT/Sources/HermesDesktop/Models"
SERVICES_DIR="$REPO_ROOT/Sources/HermesDesktop/Services"
UTILS_DIR="$REPO_ROOT/Sources/HermesDesktop/Utilities"
APP_DIR="$REPO_ROOT/Sources/HermesDesktop/App"

if [[ ! -d "$VIEWS_DIR" ]]; then
  echo "Views/ not found at $VIEWS_DIR" >&2
  exit 2
fi

# Render one inventory section.
# Args: <title> <regex> <search-dir>
section() {
  local title="$1"
  local pattern="$2"
  local dir="$3"

  echo "### $title"
  echo
  echo "| API | Count | First citation |"
  echo "|---|---:|---|"

  # Get unique matches and per-match first file:line citation.
  rg -o --no-filename --no-line-number "$pattern" "$dir" 2>/dev/null \
    | sort | uniq -c | sort -rn \
    | while read -r count match; do
        local citation
        citation="$(rg -n --no-heading "$match" "$dir" 2>/dev/null | head -1 \
          | sed -E "s|$REPO_ROOT/||" | cut -d: -f1,2)"
        printf '| `%s` | %d | %s |\n' "$match" "$count" "$citation"
      done
  echo
}

cat <<EOF
# SwiftUI API Inventory — hermes-desktop Views/

**Generated by**: \`spike/inventory.sh\`
**Source scope**: \`Sources/HermesDesktop/Views/\` (plus selected Models/Services/Utilities/App for context)
**Generated at**: $(date --iso-8601=seconds)
**Commit**: $(cd "$REPO_ROOT" && git rev-parse --short HEAD)

This is the **primary deliverable** of Phase 0. Cross-referenced against the
SwiftCrossUI tag in \`spike/swift-cross-ui-api-surface.md\` to produce
\`spike/api-gap-analysis.md\`, which drives the GO/NO-GO decision.

API categories below are deliberately overlapping (a name like \`Toggle\` will
appear under both Controls and Forms if both contexts apply); dedupe judgment
goes into the gap analysis.

---

EOF

section "View modifiers — modal & overlay" \
  '\.(sheet|alert|confirmationDialog|popover|fullScreenCover)\b' \
  "$VIEWS_DIR"

section "View modifiers — context & menu" \
  '\.(contextMenu|menuStyle|menuIndicator|menuOrder)\b' \
  "$VIEWS_DIR"

section "View modifiers — drag & drop" \
  '\.(onDrag|onDrop|draggable|dropDestination|itemProvider)\b' \
  "$VIEWS_DIR"

section "View modifiers — file dialogs" \
  '\.(fileImporter|fileExporter|fileMover)\b' \
  "$VIEWS_DIR"

section "View modifiers — focus" \
  '\.(focused|focusable|focusEffect|prefersDefaultFocus|defaultFocus|focusScope|focusSection)\b' \
  "$VIEWS_DIR"

section "View modifiers — lifecycle & async" \
  '\.(task|refreshable|onAppear|onDisappear|onChange|onReceive|onSubmit)\b' \
  "$VIEWS_DIR"

section "View modifiers — search & toolbar" \
  '\.(searchable|searchSuggestions|searchScopes|toolbar|toolbarRole|toolbarBackground|toolbarColorScheme|toolbarTitleDisplayMode)\b' \
  "$VIEWS_DIR"

section "View modifiers — navigation" \
  '\.(navigationTitle|navigationSubtitle|navigationBarTitle|navigationBarHidden|navigationBarBackButtonHidden|navigationDestination|navigationSplitViewStyle|navigationSplitViewColumnWidth|navigationBarItems|tabItem|tabViewStyle)\b' \
  "$VIEWS_DIR"

section "View modifiers — preferences & geometry" \
  '\.(onPreferenceChange|preference|transformPreference|anchorPreference|onGeometryChange|coordinateSpace|matchedGeometryEffect|alignmentGuide)\b' \
  "$VIEWS_DIR"

section "View modifiers — gestures & swipe" \
  '\.(gesture|simultaneousGesture|highPriorityGesture|swipeActions|onTapGesture|onLongPressGesture|onHover|hoverEffect)\b' \
  "$VIEWS_DIR"

section "View modifiers — accessibility" \
  '\.(accessibilityLabel|accessibilityValue|accessibilityHint|accessibilityElement|accessibilityAddTraits|accessibilityRemoveTraits|accessibilityIdentifier|accessibilityHidden|accessibilityRotor|accessibilityFocused|accessibilityAction|accessibilityRepresentation)\b' \
  "$VIEWS_DIR"

section "View modifiers — keyboard & input" \
  '\.(keyboardShortcut|disableAutocorrection|textContentType|textInputAutocapitalization|submitLabel|onSubmit)\b' \
  "$VIEWS_DIR"

section "View types — navigation" \
  '\b(NavigationStack|NavigationSplitView|NavigationView|NavigationLink|NavigationPath)\b' \
  "$VIEWS_DIR"

section "View types — layout containers" \
  '\b(VStack|HStack|ZStack|LazyVStack|LazyHStack|LazyVGrid|LazyHGrid|GeometryReader|ViewThatFits|Group|Section|Form|List|Grid|ScrollView|ScrollViewReader|ScrollViewProxy|TabView|TimelineView|Canvas|TextEditor)\b' \
  "$VIEWS_DIR"

section "View types — controls & inputs" \
  '\b(Button|TextField|SecureField|Toggle|Picker|DatePicker|ColorPicker|Stepper|Slider|ProgressView|Gauge|Menu|DisclosureGroup|Label)\b' \
  "$VIEWS_DIR"

section "View types — text & content" \
  '\b(Text|Image|Link|Divider|Spacer|EmptyView|EquatableView|AnyView)\b' \
  "$VIEWS_DIR"

section "Apple Charts (import Charts)" \
  '\b(BarMark|LineMark|PointMark|AreaMark|RuleMark|RectangleMark|SectorMark|ChartProxy|ChartLegend|AxisMarks|AxisValueLabel|AxisGridLine|AxisTick|ChartXAxis|ChartYAxis|ChartXScale|ChartYScale|ChartForegroundStyleScale|chartXAxisLabel|chartYAxisLabel)\b' \
  "$VIEWS_DIR"

section "Property wrappers" \
  '@(State|StateObject|Binding|ObservedObject|EnvironmentObject|Environment|FocusState|FocusedValue|FocusedBinding|FocusedObject|SceneStorage|AppStorage|Published|Bindable|Observable|FetchRequest|SectionedFetchRequest|Namespace|GestureState|ScaledMetric|Query|Entry)\b' \
  "$VIEWS_DIR"

section "Protocols & associated types" \
  '\b(PreferenceKey|EnvironmentKey|Layout|DynamicProperty|ViewModifier|Shape|InsettableShape|ShapeStyle|GestureType|ButtonStyle|MenuStyle|LabelStyle|TextFieldStyle|ToggleStyle|PickerStyle|ProgressViewStyle|GroupBoxStyle|FormStyle|ListStyle|ControlGroupStyle|TableStyle|TabViewStyle)\b' \
  "$VIEWS_DIR"

section "Foundation APIs likely Linux-fragile" \
  '\b(AttributedString|NSAttributedString|UTType|FormatStyle|Markdown|UTF8\.encode|FileImporter|Locale\.current)\b' \
  "$VIEWS_DIR"

section "Coordinate / animation APIs" \
  '\.(animation|withAnimation|transition|matchedGeometryEffect|transformEffect|rotationEffect|scaleEffect|offset|projectionEffect|geometryGroup)\b' \
  "$VIEWS_DIR"

# NOTE: `\b@MainActor\b` doesn't match because `\b` between two non-word chars
# (the boundary BEFORE `@`) doesn't fire. Drop the leading `\b`.
section "Concurrency & lifecycle" \
  '(@MainActor|@Sendable|@preconcurrency|@unchecked|TaskGroup|withTaskGroup|withTaskCancellationHandler|AsyncStream|AsyncSequence|AsyncThrowingStream)\b' \
  "$VIEWS_DIR"

# Same-file scans across the rest of the app for context.
echo "---"
echo
echo "## Non-Views APIs of interest (Models / Services / Utilities / App)"
echo

section "AppKit imports (must be gated or replaced)" \
  '\b(NSApplication|NSApplicationDelegate|NSWindow|NSView|NSViewRepresentable|NSViewController|NSColor|NSImage|NSFont|NSTextView|NSScrollView|NSSplitView|NSSplitViewDelegate|NSPasteboard|NSWorkspace|NSUserNotification|NSStatusItem|NSMenu|NSMenuItem|NSOpenPanel|NSSavePanel|NSAlert|NSEvent|NSCursor|NSAnimation|NSResponder)\b' \
  "$REPO_ROOT/Sources/HermesDesktop"

section "Foundation-on-Linux known gaps" \
  '\b(OSLog|os\.log|Logger|Process|FileHandle|URLSession|NSWorkspace|FileManager\.applicationSupportDirectory|NSHomeDirectory|NSTemporaryDirectory)\b' \
  "$REPO_ROOT/Sources/HermesDesktop"

section "Process spawning (must use posix_spawn + env scrub on Linux)" \
  '\b(Process\(\)|Process\.run|launchPath|executableURL|posix_spawn)\b' \
  "$REPO_ROOT/Sources/HermesDesktop"

echo "---"
echo
echo "## Aggregate counts"
echo
echo "| Metric | Value |"
echo "|---|---:|"
printf '| Views/ files | %d |\n' \
  "$(find "$VIEWS_DIR" -type f -name '*.swift' | wc -l)"
printf '| Views/ LOC | %d |\n' \
  "$(find "$VIEWS_DIR" -type f -name '*.swift' -print0 | xargs -0 wc -l 2>/dev/null | tail -1 | awk '{print $1}')"
# `import X` may be preceded by import attributes like `@preconcurrency`.
import_count() {
  local module="$1"
  rg -l "(^|^@[A-Za-z_][A-Za-z0-9_]*\s+)import\s+${module}\b" \
    "$REPO_ROOT/Sources/HermesDesktop" 2>/dev/null | wc -l
}
printf '| Files importing AppKit | %d |\n' "$(import_count AppKit)"
printf '| Files importing Charts | %d |\n' "$(import_count Charts)"
printf '| Files importing SwiftUI | %d |\n' "$(import_count SwiftUI)"
printf '| Files importing SwiftTerm | %d |\n' "$(import_count SwiftTerm)"
printf '| Files importing OSLog | %d |\n' "$(import_count OSLog)"
printf '| Files importing CryptoKit | %d |\n' "$(import_count CryptoKit)"
printf '| Files importing Crypto (swift-crypto) | %d |\n' "$(import_count Crypto)"
echo
